sonar.organization=modsmthng
sonar.projectKey=modsmthng_MyBrewFolio-Sync

sonar.sources=src,src-tauri/src

sonar.exclusions=\
  **/node_modules/**,\
  **/target/**,\
  **/dist/**

sonar.rust.cargo.manifestPaths=src-tauri/Cargo.toml
